# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gangjuseong/Desktop/study/3-1/객분설/OOAD_Project/UI/LoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(850, 500)
        LoginScreen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title_label = QtWidgets.QLabel(LoginScreen)
        self.title_label.setGeometry(QtCore.QRect(230, 80, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title_label.setFont(font)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.id_label = QtWidgets.QLabel(LoginScreen)
        self.id_label.setGeometry(QtCore.QRect(190, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.id_label.setFont(font)
        self.id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label.setObjectName("id_label")
        self.pw_label = QtWidgets.QLabel(LoginScreen)
        self.pw_label.setGeometry(QtCore.QRect(190, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pw_label.setFont(font)
        self.pw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pw_label.setObjectName("pw_label")
        self.id_edit = QtWidgets.QLineEdit(LoginScreen)
        self.id_edit.setGeometry(QtCore.QRect(280, 190, 311, 31))
        self.id_edit.setObjectName("id_edit")
        self.pw_edit = QtWidgets.QLineEdit(LoginScreen)
        self.pw_edit.setGeometry(QtCore.QRect(280, 250, 311, 31))
        self.pw_edit.setObjectName("pw_edit")
        self.login_btn = QtWidgets.QPushButton(LoginScreen)
        self.login_btn.setGeometry(QtCore.QRect(270, 310, 161, 51))
        self.login_btn.setObjectName("login_btn")
        self.signup_btn = QtWidgets.QPushButton(LoginScreen)
        self.signup_btn.setGeometry(QtCore.QRect(430, 310, 161, 51))
        self.signup_btn.setObjectName("signup_btn")

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "무인 도서 관리 시스템"))
        self.title_label.setText(_translate("LoginScreen", "무인 도서 관리 시스템"))
        self.id_label.setText(_translate("LoginScreen", "EMAIL : "))
        self.pw_label.setText(_translate("LoginScreen", "PW : "))
        self.login_btn.setText(_translate("LoginScreen", "로그인"))
        self.signup_btn.setText(_translate("LoginScreen", "회원가입"))
