# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gangjuseong/Desktop/study/3-1/객분설/OOAD_Project/UI/MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(1500, 1000)
        self.title_label = QtWidgets.QLabel(MainScreen)
        self.title_label.setGeometry(QtCore.QRect(550, 20, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title_label.setFont(font)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.BookList = QtWidgets.QListView(MainScreen)
        self.BookList.setGeometry(QtCore.QRect(70, 180, 511, 701))
        self.BookList.setObjectName("BookList")
        self.book_list_label = QtWidgets.QLabel(MainScreen)
        self.book_list_label.setGeometry(QtCore.QRect(70, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.book_list_label.setFont(font)
        self.book_list_label.setObjectName("book_list_label")
        self.lineEdit = QtWidgets.QLineEdit(MainScreen)
        self.lineEdit.setGeometry(QtCore.QRect(170, 120, 331, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(MainScreen)
        self.pushButton.setGeometry(QtCore.QRect(510, 120, 71, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "무인 도서 관리 시스템"))
        self.title_label.setText(_translate("MainScreen", "무인 도서 관리 시스템"))
        self.book_list_label.setText(_translate("MainScreen", "도서 목록"))
        self.lineEdit.setPlaceholderText(_translate("MainScreen", "도서명, 저자명, ISBN으로 검색"))
        self.pushButton.setText(_translate("MainScreen", "Search"))
