# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gangjuseong/Desktop/study/3-1/객분설/OOAD_Project/UI/MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(1440, 783)
        self.title_label = QtWidgets.QLabel(MainScreen)
        self.title_label.setGeometry(QtCore.QRect(550, 20, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title_label.setFont(font)
        self.title_label.setTextFormat(QtCore.Qt.AutoText)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.book_list_label = QtWidgets.QLabel(MainScreen)
        self.book_list_label.setGeometry(QtCore.QRect(70, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.book_list_label.setFont(font)
        self.book_list_label.setObjectName("book_list_label")
        self.search_edit = QtWidgets.QLineEdit(MainScreen)
        self.search_edit.setGeometry(QtCore.QRect(170, 120, 331, 41))
        self.search_edit.setText("")
        self.search_edit.setObjectName("search_edit")
        self.search_btn = QtWidgets.QPushButton(MainScreen)
        self.search_btn.setGeometry(QtCore.QRect(510, 120, 71, 41))
        self.search_btn.setObjectName("search_btn")
        self.user_name_label = QtWidgets.QLabel(MainScreen)
        self.user_name_label.setGeometry(QtCore.QRect(70, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.user_name_label.setFont(font)
        self.user_name_label.setObjectName("user_name_label")
        self.book_list = QtWidgets.QListWidget(MainScreen)
        self.book_list.setGeometry(QtCore.QRect(70, 170, 501, 591))
        self.book_list.setObjectName("book_list")
        self.book_name_label = QtWidgets.QLabel(MainScreen)
        self.book_name_label.setGeometry(QtCore.QRect(590, 170, 231, 31))
        self.book_name_label.setObjectName("book_name_label")
        self.book_author_label = QtWidgets.QLabel(MainScreen)
        self.book_author_label.setGeometry(QtCore.QRect(590, 210, 231, 31))
        self.book_author_label.setObjectName("book_author_label")
        self.book_isbn_label = QtWidgets.QLabel(MainScreen)
        self.book_isbn_label.setGeometry(QtCore.QRect(590, 250, 231, 31))
        self.book_isbn_label.setObjectName("book_isbn_label")
        self.book_rental_label = QtWidgets.QLabel(MainScreen)
        self.book_rental_label.setGeometry(QtCore.QRect(590, 290, 231, 31))
        self.book_rental_label.setObjectName("book_rental_label")
        self.book_location_label = QtWidgets.QLabel(MainScreen)
        self.book_location_label.setGeometry(QtCore.QRect(590, 330, 231, 31))
        self.book_location_label.setObjectName("book_location_label")

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "무인 도서 관리 시스템"))
        self.title_label.setText(_translate("MainScreen", "무인 도서 관리 시스템"))
        self.book_list_label.setText(_translate("MainScreen", "도서 목록"))
        self.search_edit.setPlaceholderText(_translate("MainScreen", "도서명, 저자명, ISBN으로 검색"))
        self.search_btn.setText(_translate("MainScreen", "Search"))
        self.user_name_label.setText(_translate("MainScreen", "님, 안녕하세요."))
        self.book_name_label.setText(_translate("MainScreen", "책 이름 : "))
        self.book_author_label.setText(_translate("MainScreen", "저자 : "))
        self.book_isbn_label.setText(_translate("MainScreen", "ISBN : "))
        self.book_rental_label.setText(_translate("MainScreen", "대여 상태 : "))
        self.book_location_label.setText(_translate("MainScreen", "위치 : "))
